#???8010
server:
  port: 8090
    #address: 116.204.36.31
  # swagger端口号

#?????mysql????root???123456
spring:
  datasource:
    username: root # 数据库账号
    password: 'Tank123123' # 数据库密码
    url: jdbc:mysql://116.204.36.31:3306/crosschain_database?serverTimezone=GMT%2B8&amp;characterEncoding=utf-8 # 数据库IP和端口
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus??
mybatis-plus:
  # xml????
  mapper-locations: classpath:mapper/*.xml