chain_client:
  # 链ID
  chain_id: "chainmaker_testnet_chain"
  # 组织ID
  org_id: "org5.cmtestnet"
  # 客户端用户私钥路径
  user_key_file_path: "src/main/resources/crypto-config/org5.cmtestnet/user/client/hou_tls.key"
  # 客户端用户证书路径
  user_crt_file_path: "src/main/resources/crypto-config/org5.cmtestnet/user/client/hou_tls.crt"
  # 客户端用户交易签名私钥路径(若未设置，将使用user_key_file_path)
  user_sign_key_file_path: "src/main/resources/crypto-config/org5.cmtestnet/user/client/hou_sign.key"
  # 客户端用户交易签名证书路径(若未设置，将使用user_crt_file_path)
  user_sign_crt_file_path: "src/main/resources/crypto-config/org5.cmtestnet/user/client/hou_sign.crt"

  retry_limit: 10
  # 同步交易结果模式下，每次轮训交易结果时的等待时间，单位：ms 删除此项或设为<=0则使用默认值 500
  retry_interval: 500
  # 当前签名证书的别名。当设置此配置项时，chain client 对象将自动检查链上是否已添加此别名，如果没有则自动上链此证书别名，
  # 并且后续所有交易都会使用别名，别名可降低交易体大小。若为空则不启用。
  #  alias: mycert5
  nodes:
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "172.21.0.6:12301"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "src/main/resources/crypto-config/org5.cmtestnet/ca/org1.cmtestnet"
      # TLS hostname
      tls_host_name: "consensus1.tls.org1.cmtestnet"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "172.21.0.11:12301"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "src/main/resources/crypto-config/org5.cmtestnet/ca/org2.cmtestnet"
      # TLS hostname
      tls_host_name: "consensus1.tls.org2.cmtestnet"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "172.21.0.7:12301"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "src/main/resources/crypto-config/org5.cmtestnet/ca/org3.cmtestnet"
      # TLS hostname
      tls_host_name: "consensus1.tls.org3.cmtestnet"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "172.21.0.17:12301"
      # 节点连接数
      conn_cnt: 10
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径
      trust_root_paths:
        - "src/main/resources/crypto-config/org5.cmtestnet/ca/org4.cmtestnet"
      # TLS hostname
      tls_host_name: "consensus1.tls.org4.cmtestnet"
  archive:
    # mysql archivecenter 归档中心 数据归档链外存储相关配置
    type: "mysql"
    dest: "root:123456:localhost:3306"
    secret_key: xxx
  # 如果为true且归档中心配置打开,那么查询数据优先从归档中心查询
  # 如果是false,则不访问归档中心，只访问链数据
  archive_center_query_first: false
  # 归档中心
  archive_center_config:
    chain_genesis_hash: a23a0c6fd402010efbc31741b2a868c9e6558471fda1e8d1f16673ef683e06db
    archive_center_http_url: http://127.0.0.1:13119
    request_second_limit: 10
    rpc_address: 127.0.0.1:13120
    tls_enable: false
    tls:
      server_name: archiveserver1.tls.wx-org.chainmaker.org
      priv_key_file: src/test/resources/archivecenter/archiveclient1.tls.key
      cert_file: src/test/resources/archivecenter/archiveclient1.tls.crt
      trust_ca_list:
        - src/test/resources/archivecenter/ca
    max_send_msg_size: 200
    max_recv_msg_size: 200

  rpc_client:
    # grpc客户端最大接受容量(MB)
    max_receive_message_size: 16

  pkcs11:
    enabled: false # pkcs11 is not used by default

  # 交易结果是否订阅获取
  enable_tx_result_dispatcher: true

  ##连接池配置
  connPool:
    # 最大连接数
    maxTotal: 100
    # 最少空闲连接
    minIdle: 1
    #最大空闲连接
    maxIdle: 20
    #连接空闲最小保活时间，默认即为30分钟(18000000)，单位：ms
    minEvictableIdleTime: 350000
    #回收空闲线程的执行周期，单位毫秒。默认值60000ms（60s） ，-1 表示不启用线程回收资源，单位：ms
    timeBetweenEvictionRuns: 60000
    #没有空闲连接时，获取连接是否阻塞
    blockWhenExhausted: true
    #当没有空闲连接时，获取连接阻塞等待时间，单位：ms
    maxWaitMillis: 3000

